### ISSUE TITLE
Loading script only works for macos

### ISSUE THREAD

**Issue by LnnrtS** [4ms/mp1-boot#2]
Partition naming scheme is different to linux: `sX` vs `pX`

`diskutil` is not available onlinux. But since we are writing to raw block devices there is nothing to unmount anyway. To be sure all buffers are flushed we could just call `dd` with `conv=fdatasync`.

**Comment by danngreen** [comment]
Right...
I'm pretty sure all partition naming conventions will append a digit at the end to indicate the partition number. So we could take the device "stem" and then append 1 or 2 to it. Something like:
`make load SD_DISK_STEM=/dev/mmcblk0p` which would load to `mmcblk0p1` and `mmcblk0p2`.
 
The reason for unmounting is to speed up the build-flash-test cycle, since it's impossible to test some aspects of a bootloader using a debugger. But I want to keep this simple, so we can just have the dev `make load SD_DISK_STEM=/dev/XXXp && os-specific-unmount-cmd /dev/XXX`.

**Comment by danngreen** [comment]
There's a FATFS partition (not required, but the format script creates it), so the OS typically will automatically mount this when the card is inserted.
